### ISSUE TITLE
Typo in genome viewer widget

### ISSUE THREAD

**Issue by jeffkimbrel** [kbase/narrative#1487] opened 2019-06-12 15:45 UTC
Hello, can you please fix the typo in the genome view widget at the following line? Should be 'Hydrophobic' rather than 'Hyrdrophobic'.

https://github.com/kbase/narrative/blob/cd5b46d8c1822925c8f0104456de10324bb430b8/kbase-extension/static/kbase/js/widgets/function_output/kbaseGenomeAnnotation.js#L1478

Screen shot of problem:

<img width="823" alt="image" src="https://user-images.githubusercontent.com/10132972/59365944-4c329800-8cee-11e9-8821-cee1afcc2b7f.png">

Thanks!

**Comment by meghandrake** [comment] 2019-06-12 17:10
Jeff, thanks for letting us know!  A pull request just was submitted to fix it! When it's merged you will get an email, as well as when the issue is closed.

**Comment by briehl** [comment] 2019-06-12 20:53
The fix is up on CI now, looks like it works.

**Comment by briehl** [comment] 2019-06-13 19:26
Fixed and on the deployment path. Thanks for bringing this up, @jeffkimbrel!

**Closed** 2019-06-13 19:26 UTC
